---
title: "Untitled"
author: "JK4529"
date: "2024-04-01"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(ggrepel)
library(Hmisc)
library(prettyR)
library(rcompanion)
library(dplyr)
library(ggplot2)
library(TukeyC)
library(tidyr)
library(plotly)
library(forcats)
```
# datasets
```{r}
df1 <- read.csv('C:/Users/cptas/Downloads/Experiment_003subset_eval_table.csv')
df1$institution <- sub('\\..*', '', df1$sample_id)
df1$gpt_version <-  factor(df1$gpt_version, levels = c('llama-2-7b-chat', 'llama-2-13b-chat', 'llama-2-70b-chat', 'gpt-3.5-turbo', 'gpt-4'))
df2 <- read.csv('C:/Users/cptas/Downloads/Experiment_replicate_0222_prev_eval_table.csv')
df2$institution <- sub('\\..*', '', df2$sample_id)
df2$gpt_version <-  factor(df2$gpt_version, levels = c('llama-2-7b-chat', 'llama-2-13b-chat', 'llama-2-70b-chat', 'gpt-3.5-turbo', 'gpt-4'))

df1_d <- df1 %>% filter(prompt == 'd')

df <- rbind(df1, df2)
df_d <- rbind(df1_d, df2)
dim(df2)
dim(df1)
```

# Figure 2 & oacc/acc by llm models
```{r}
df_d_oacc <- df_d %>%
  group_by(gpt_version, top_n) %>%
  summarise(n = n(),
            o_acc = sum(accuracy == 1, na.rm = T),
            o_acc_ratio = round((o_acc/n)*100, 1)) %>%
  ungroup() %>%
  select(gpt_version, top_n, o_acc_ratio)
df_d_oacc

df_d_acc <-df_d %>%
  filter(completeness == 1) %>%
  group_by(gpt_version, top_n) %>%
  summarise(n = n(),
            acc = sum(accuracy == 1, na.rm = T),
            acc_ratio = round((acc/n)*100, 1)) %>%
  ungroup() %>%
  select(gpt_version, top_n, acc_ratio)
df_d_acc


df_d_combine_acc <- left_join(df_d_oacc, df_d_acc, by = c("gpt_version", "top_n"))
df_d_combine_acc$top_n <- as.character(df_d_combine_acc$top_n)
df_d_combine_acc

df_d_long <- df_d_combine_acc %>%
  pivot_longer(cols = c(o_acc_ratio, acc_ratio), names_to = "type", values_to = "value") %>%
  drop_na(value) %>%
  mutate(
    type = ifelse(type == "o_acc_ratio", "OACC", "ACC"),
    category = paste(top_n, type, sep = " ")
  )
df_d_long$category <- factor(df_d_long$category, levels = c("10 OACC", "10 ACC", "50 OACC", "50 ACC"))
df_d_long


ggplot(df_d_long, aes(x = gpt_version, y = value, fill = category)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.75)) +
  scale_fill_manual(values = c(
    "10 OACC" = "#56B4E9",  
    "10 ACC" = "#E69F00",   
    "50 OACC" = "#009E73",  
    "50 ACC" = "#F0E442"    
  )) +
  labs(x = "Model & Version", y = "Accuracy Rate (%)", fill = "Category") +
  theme(legend.position = "none")
```
# Figure 3
```{r}
g4_oa <- df1 %>% 
  filter(input_type == 'hpo_concepts' & gpt_version == 'gpt-4' & institution != 'TAF1') %>%
  group_by(institution, top_n) %>%
  summarise(n = n(),
            oacc = round(sum(accuracy == 1, na.rm = TRUE)/n * 100, 1)) %>%
  select(institution, top_n, oacc)


g4_a <- df1 %>% 
  filter(input_type == 'hpo_concepts' & gpt_version == 'gpt-4' & completeness == 1 & institution != 'TAF1') %>%
  group_by(institution, top_n) %>%
  summarise(n = n(),
            acc = round(sum(accuracy == 1, na.rm = TRUE)/n * 100, 1))%>%
  select(institution, top_n, acc)


g4 <- left_join(g4_oa, g4_a, by = c("institution", "top_n"))
g4$top_n <- as.character(g4$top_n)
g4_long <- g4 %>%
  pivot_longer(cols = c(oacc, acc), names_to = "type", values_to = "value") %>%
  drop_na(value) %>%
  mutate(
    type = ifelse(type == "oacc", "OACC", "ACC"),
    category = paste(top_n, type, sep = " ")
  )
g4_long$category <- factor(g4_long$category, levels = c("10 OACC", "10 ACC", "50 OACC", "50 ACC"))



ggplot(g4_long, aes(x = institution, y = value, fill = category)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.75)) +
  scale_fill_manual(values = c(
    "10 OACC" = "#56B4E9",  
    "10 ACC" = "#E69F00",   
    "50 OACC" = "#009E73",  
    "50 ACC" = "#F0E442"    
  )) +
  labs(x = "Institution", y = "Accuracy Rate (%)", fill = "Category") +
  theme(legend.position = "none")
```

# Figure 4
```{r}
df1_d2 <- df1_d
df1_d2$institution <- ifelse(df1_d2$institution == 'AJHG' | df1_d2$institution == 'CSH', 'AJHG/CSH', df1_d2$institution)
df1_group_acc <- df1_d2  %>% filter(input_type == 'hpo_concepts')%>%
  select(institution, top_n, gpt_version, accuracy) %>%
  group_by(institution, top_n, gpt_version) %>%
  summarise(n = n(),
            acc = sum(accuracy == 1, na.rm = TRUE),
            acc_ratio = round((acc/n)*100,1)) %>%
  select('institution', 'top_n', 'gpt_version', 'acc_ratio')
  

df2_2 <- df2
df2_2$institution <- ifelse(df2_2$institution == 'AJHG' | df2_2$institution == 'CSH', 'AJHG/CSH', df2_2$institution)
df2_group_acc <- df2_2  %>% filter(input_type == 'hpo_concepts')%>%
  select(institution, top_n, gpt_version, accuracy) %>%
  group_by(institution, top_n, gpt_version) %>%
  summarise(n = n(),
            acc = sum(accuracy == 1, na.rm = TRUE),
            acc_ratio = round((acc/n)*100,1)) %>%
  select('institution', 'top_n', 'gpt_version', 'acc_ratio')

df_group_acc <- rbind(df1_group_acc, df2_group_acc)

new_rows <- data.frame(
  'institution' = c('AJHG/CSH','AJHG/CSH','AJHG/CSH','AJHG/CSH','AJHG/CSH','AJHG/CSH','AJHG/CSH','AJHG/CSH','ColumbiaU','ColumbiaU','ColumbiaU','ColumbiaU','ColumbiaU','ColumbiaU','ColumbiaU','ColumbiaU','DGD','DGD','DGD','DGD','DGD','DGD','DGD','DGD','TAF1','TAF1','TAF1','TAF1','TAF1','TAF1','TAF1','TAF1'), 
  'top_n' = c(10,10,10,10,50,50,50,50,10,10,10,10,50,50,50,50,10,10,10,10,50,50,50,50,10,10,10,10,50,50,50,50), 
  'gpt_version' = c('Phen2Gene','Phenolyzer','AMELIE','GADO','Phen2Gene','Phenolyzer','AMELIE','GADO','Phen2Gene','Phenolyzer','AMELIE','GADO','Phen2Gene','Phenolyzer','AMELIE','GADO','Phen2Gene','Phenolyzer','AMELIE','GADO','Phen2Gene','Phenolyzer','AMELIE','GADO','Phen2Gene','Phenolyzer','AMELIE','GADO','Phen2Gene','Phenolyzer','AMELIE','GADO'),
  'acc_ratio' = c(32.1,19.2,22.4,15.4,47.4,28.2,33.3,35.3,51.9,29.6,51.9,40.7,66.7,40.7,74.1,70.4,35.3,18.8,62.4,16.5,55.3,28.2,84.7,55.3,100,0,100,100,100,0,100,100))

df_group_acc <- rbind(df_group_acc, new_rows)
df_group_acc$gpt_version <-  factor(df_group_acc$gpt_version, levels = c('llama-2-7b-chat', 'llama-2-13b-chat', 'llama-2-70b-chat', 'gpt-3.5-turbo', 'gpt-4', 'Phen2Gene', 'Phenolyzer', 'AMELIE', 'GADO'))
df_group_acc$llm <- ifelse(df_group_acc$gpt_version %in% c('llama-2-7b-chat', 'llama-2-13b-chat', 'llama-2-70b-chat', 'gpt-3.5-turbo', 'gpt-4'),1,0)

df_group_acc_ac10 <- df_group_acc %>% filter(institution == 'AJHG/CSH' & top_n == 10)
df_group_acc_ac50 <- df_group_acc %>% filter(institution == 'AJHG/CSH' & top_n == 50)
df_group_acc_cu10 <- df_group_acc %>% filter(institution == 'ColumbiaU' & top_n == 10)
df_group_acc_cu50 <- df_group_acc %>% filter(institution == 'ColumbiaU' & top_n == 50)
df_group_acc_dgd10 <- df_group_acc %>% filter(institution == 'DGD' & top_n == 10)
df_group_acc_dgd50 <- df_group_acc %>% filter(institution == 'DGD' & top_n == 50)
df_group_acc_taf10 <- df_group_acc %>% filter(institution == 'TAF1' & top_n == 10)
df_group_acc_taf50 <- df_group_acc %>% filter(institution == 'TAF1' & top_n == 50)

cb_friendly_colors <- c("#E69F00", "#56B4E9")
c2 <- ggplot(df_group_acc_dgd50, aes(x = gpt_version, y = acc_ratio, color = as.factor(llm))) +
  geom_point(size = 3) +  
  scale_color_manual(values = cb_friendly_colors) +
  geom_text_repel(aes(label = paste(gpt_version, ',', round(acc_ratio, 1), '%')),
                  size = 2.2,  # Adjust text size
                  box.padding = unit(0.35, "lines"),
                  point.padding = unit(0.5, "lines")) + 
  theme_minimal() +
  theme(legend.position = "none",
         axis.text.x = element_blank(),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +  
  ylim(0, 90) +
  geom_rect(xmin = 0.5, xmax = 5.7, ymin = 0, ymax = 30, alpha = 0.2, color = 'darkblue', linetype = "dashed", fill = NA, linewidth = 0.8) +
  geom_rect(xmin = 5.5, xmax = 9.5, ymin = 22, ymax = 89, alpha = 0.2, color = 'brown', linetype = "dashed", fill = NA, linewidth = 0.8)
c2
```

# Overall Accuacy top10
```{r}
df1 %>% filter(gpt_version == 'gpt-3.5-turbo' & top_n == 10) %>%
  select(accuracy) %>%
  group_by(prompt) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-3.5-turbo' & top_n == 10)%>%
  select(accuracy) %>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-3.5-turbo' & top_n == 10)%>%
  select(accuracy) %>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4' & top_n == 10)%>%
  select(accuracy) %>%
  group_by(prompt) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4' & top_n == 10)%>%
  select(accuracy) %>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4' & top_n == 10)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-7b-chat' & top_n == 10)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-7b-chat' & top_n == 10)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-13b-chat' & top_n == 10)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-13b-chat' & top_n == 10)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-70b-chat' & top_n == 10)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-70b-chat' & top_n == 10)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))
```

# Overall Accuacy top50
```{r}
df1 %>% filter(gpt_version == 'gpt-3.5-turbo' & top_n == 50)%>%
  group_by(prompt) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-3.5-turbo' & top_n == 50)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-3.5-turbo' & top_n == 50)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4' & top_n == 50)%>%
  group_by(prompt) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4' & top_n == 50)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4' & top_n == 50)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-7b-chat' & top_n == 50)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-7b-chat' & top_n == 50)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-13b-chat' & top_n == 50)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-13b-chat' & top_n == 50)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-70b-chat' & top_n == 50)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-70b-chat' & top_n == 50)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))
```

# Completed Accuacy top10
```{r}
df1 %>% filter(gpt_version == 'gpt-3.5-turbo' & top_n == 10 & completeness == 1)%>%
  group_by(prompt) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-3.5-turbo' & top_n == 10 & completeness == 1)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-3.5-turbo' & top_n == 10 & completeness == 1)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4' & top_n == 10 & completeness == 1)%>%
  group_by(prompt) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4' & top_n == 10 & completeness == 1)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4' & top_n == 10 & completeness == 1)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-7b-chat' & top_n == 10 & completeness == 1)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-7b-chat' & top_n == 10 & completeness == 1)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-13b-chat' & top_n == 10 & completeness == 1)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-13b-chat' & top_n == 10 & completeness == 1)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-70b-chat' & top_n == 10 & completeness == 1)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-70b-chat' & top_n == 10 & completeness == 1)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))
```

# Completed Accuacy top50
```{r}
df1 %>% filter(gpt_version == 'gpt-3.5-turbo' & top_n == 50 & completeness == 1)%>%
  group_by(prompt) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-3.5-turbo' & top_n == 50 & completeness == 1)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-3.5-turbo' & top_n == 50 & completeness == 1)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4' & top_n == 50 & completeness == 1)%>%
  group_by(prompt) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4' & top_n == 50 & completeness == 1)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4' & top_n == 50 & completeness == 1)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-7b-chat' & top_n == 50 & completeness == 1)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-7b-chat' & top_n == 50 & completeness == 1)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-13b-chat' & top_n == 50 & completeness == 1)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-13b-chat' & top_n == 50 & completeness == 1)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-70b-chat' & top_n == 50 & completeness == 1)%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-70b-chat' & top_n == 50 & completeness == 1)%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(accuracy == 1) / n * 100, 2)) %>%
  arrange(desc(rate))
```

# Completeness
```{r}
df1 %>% filter(gpt_version == 'gpt-3.5-turbo')%>%
  group_by(prompt) %>%
  summarise(n = n(),
            rate = round(sum(completeness == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-3.5-turbo')%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(completeness == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-3.5-turbo')%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(completeness == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4')%>%
  group_by(prompt) %>%
  summarise(n = n(),
            rate = round(sum(completeness == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4')%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(completeness == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df1 %>% filter(gpt_version == 'gpt-4')%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(completeness == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-7b-chat')%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(completeness == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-7b-chat')%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(completeness == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-13b-chat')%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(completeness == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-13b-chat')%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(completeness == 1) / n * 100, 2)) %>%
  arrange(desc(rate))


df2 %>% filter(gpt_version == 'llama-2-70b-chat')%>%
  group_by(top_n) %>%
  summarise(n = n(),
            rate = round(sum(completeness == 1) / n * 100, 2)) %>%
  arrange(desc(rate))

df2 %>% filter(gpt_version == 'llama-2-70b-chat')%>%
  group_by(input_type) %>%
  summarise(n = n(),
            rate = round(sum(completeness == 1) / n * 100, 2)) %>%
  arrange(desc(rate)) 
```


# Str_compliance
```{r}
summarize_data_gpt3.5 <- function(df, group_var) {
  df %>%
    filter(gpt_version == 'gpt-3.5-turbo') %>%
    group_by({{group_var}}) %>%
    summarise(n = n(),
              rate = round((sum(structural_compliance == 1) / n) * 100, 2)) %>%
    arrange(desc(rate)) %>%
    mutate(percentage = paste0(rate, '%'))
}

summarize_data_gpt4 <- function(df, group_var) {
  df %>%
    filter(gpt_version == 'gpt-4') %>%
    group_by({{group_var}}) %>%
    summarise(n = n(),
              rate = round((sum(structural_compliance == 1) / n) * 100, 2)) %>%
    arrange(desc(rate)) %>%
    mutate(percentage = paste0(rate, '%'))
}

summarize_data_l7b <- function(df, group_var) {
  df %>%
    filter(gpt_version == 'llama-2-7b-chat') %>%
    group_by({{group_var}}) %>%
    summarise(n = n(),
              rate = round((sum(structural_compliance == 1) / n) * 100, 2)) %>%
    arrange(desc(rate)) %>%
    mutate(percentage = paste0(rate, '%'))
}

summarize_data_113b <- function(df, group_var) {
  df %>%
    filter(gpt_version == 'llama-2-13b-chat') %>%
    group_by({{group_var}}) %>%
    summarise(n = n(),
              rate = round((sum(structural_compliance == 1) / n) * 100, 2)) %>%
    arrange(desc(rate)) %>%
    mutate(percentage = paste0(rate, '%'))
}

summarize_data_l70b <- function(df, group_var) {
  df %>%
    filter(gpt_version == 'llama-2-70b-chat') %>%
    group_by({{group_var}}) %>%
    summarise(n = n(),
              rate = round((sum(structural_compliance == 1) / n) * 100, 2)) %>%
    arrange(desc(rate)) %>%
    mutate(percentage = paste0(rate, '%'))
}

summary_3.5_prompt <- summarize_data_gpt3.5(df1, prompt)
summary_3.5_top_n <- summarize_data_gpt3.5(df1, top_n)
summary_3.5_input_type <- summarize_data_gpt3.5(df1, input_type)
summary_4_prompt <- summarize_data_gpt4(df1, prompt)
summary_4_top_n <- summarize_data_gpt4(df1, top_n)
summary_4_input_type <- summarize_data_gpt4(df1, input_type)
summary_l7b_top_n <- summarize_data_l7b(df2, top_n)
summary_l7b_input_type <- summarize_data_l7b(df2, input_type)
summary_l13b_top_n <- summarize_data_113b(df2, top_n)
summary_l13b_input_type <- summarize_data_113b(df2, input_type)
summary_l70b_top_n <- summarize_data_l70b(df2, top_n)
summary_l70b_input_type <- summarize_data_l70b(df2, input_type)


summary_3.5_prompt
summary_3.5_top_n
summary_3.5_input_type
summary_4_prompt
summary_4_top_n
summary_4_input_type
summary_l7b_top_n
summary_l7b_input_type
summary_l13b_top_n
summary_l13b_input_type
summary_l70b_top_n
summary_l70b_input_type
```


# Institution
```{r}
df_d %>% 
  filter(top_n == 10 & input_type == 'hpo_concepts') %>% 
  group_by(institution, gpt_version) %>%
  summarise(n = n(),
            oacc = round((sum(accuracy == 1, na.rm = T) / n) * 100, 2))

df_d %>% 
  filter(top_n == 50 & input_type == 'hpo_concepts') %>% 
  group_by(institution, gpt_version) %>%
  summarise(n = n(),
            oacc = round((sum(accuracy == 1, na.rm = T) / n) * 100, 2))

df_d %>% 
  filter(completeness == 1 & top_n == 10 & input_type == 'hpo_concepts') %>%
  group_by(institution, gpt_version) %>%
  summarise(n = n(),
            acc = round((sum(accuracy == 1, na.rm = T) / n) * 100, 2))

df_d %>% 
  filter(completeness == 1 & top_n == 50 & input_type == 'hpo_concepts') %>%
  group_by(institution, gpt_version) %>%
  summarise(n = n(),
            acc = round((sum(accuracy == 1, na.rm = T) / n) * 100, 2))

df_d %>% filter(input_type == 'hpo_concepts') %>%
  select(institution, completeness) %>%
  group_by(institution) %>%
  summarise(n = n(),
            rate = sum(completeness == 1) / n) %>%
  arrange(desc(rate))

df_d %>% filter(input_type == 'hpo_concepts') %>%
  select(institution, structural_compliance) %>%
  group_by(institution) %>%
  summarise(n = n(),
            rate = sum(structural_compliance == 1) / n) %>%
  arrange(desc(rate))
```


# Gene & Supp1
```{r}
M <- dim(df_d)[1]
K <- dim(df_d %>% filter(accuracy == 1))[1]
M
K

```


```{r}
g4_or <- df_d %>% filter(gpt_version == 'gpt-4') %>%
  group_by(true_gene) %>%
  summarise(m = n(),
            k = sum(accuracy == 1, na.rm = TRUE),
            K = K,
            M = M,
            OR = (k / K) / (m / M)) %>%
  arrange(desc(OR))
g4_or$model <- rep('gpt-4', 165)

g3_or <- df_d %>% filter(gpt_version == 'gpt-3.5-turbo') %>%
  group_by(true_gene) %>%
  summarise(m = n(),
            k = sum(accuracy == 1, na.rm = TRUE),
            K = K,
            M = M,
            OR = (k / K) / (m / M)) %>%
  arrange(desc(OR))
g3_or$model <- rep('gpt-3.5-turbo', 165)


l7_or <- df_d %>% filter(gpt_version == 'llama-2-7b-chat') %>%
  group_by(true_gene) %>%
  summarise(m = n(),
            k = sum(accuracy == 1, na.rm = TRUE),
            K = K,
            M = M,
            OR = (k / K) / (m / M)) %>%
  arrange(desc(OR))
l7_or$model <- rep('llama-2-7b-chat', 165)


l13_or <- df_d %>% filter(gpt_version == 'llama-2-13b-chat') %>%
  group_by(true_gene) %>%
  summarise(m = n(),
            k = sum(accuracy == 1, na.rm = TRUE),
            K = K,
            M = M,
            OR = (k / K) / (m / M)) %>%
  arrange(desc(OR))
l13_or$model <- rep('llama-2-13b-chat', 165)


l70_or <- df_d %>% filter(gpt_version == 'llama-2-70b-chat') %>%
  group_by(true_gene) %>%
  summarise(m = n(),
            k = sum(accuracy == 1, na.rm = TRUE),
            K = K,
            M = M,
            OR = (k / K) / (m / M)) %>%
  arrange(desc(OR))
l70_or$model <- rep('llama-2-70b-chat', 165)


or_model <- rbind(g4_or, g3_or, l7_or, l13_or, l70_or)
```


# Supp2
```{r}
avg_sd <- function(df, a, b, c, d) {
  df %>%
    filter(gpt_version == a, input_type == b, prompt == c, top_n == d) %>%
    summarise(n = n(),
              comp_avg = round(mean(completeness == 1, na.rm = TRUE) * 100, 2),
              comp_sd = round(sd(completeness, na.rm = TRUE),2),
              oacc_avg = round(sum(accuracy == 1, na.rm = TRUE)/n * 100, 2),
              oacc_sd = round(sqrt(sum(accuracy == 1, na.rm = TRUE) * (1 - sum(accuracy == 1, na.rm = TRUE) / n) / n),2),
              str_avg = round(mean(structural_compliance == 1, na.rm = TRUE) * 100, 2),
              str_sd = round(sd(structural_compliance, na.rm = TRUE),2)
              )
}

avg_sd_acc <- function(df, a, b, c, d) {
  df %>%
    filter(completeness == 1, gpt_version == a, input_type == b, prompt == c, top_n == d) %>%
    summarise(n = n(),
              acc_avg = round(sum(accuracy == 1, na.rm = TRUE)/n * 100, 2),
              acc_sd = round(sd(accuracy, na.rm = TRUE),2)
              )
}

avg_sd(df1, 'gpt-4', 'hpo_concepts', 'a', 10)
avg_sd(df1, 'gpt-4', 'hpo_concepts', 'a', 50)
avg_sd(df1, 'gpt-4', 'hpo_concepts', 'b', 10)
avg_sd(df1, 'gpt-4', 'hpo_concepts', 'b', 50)
avg_sd(df1, 'gpt-4', 'hpo_concepts', 'c', 10)
avg_sd(df1, 'gpt-4', 'hpo_concepts', 'c', 50)
avg_sd(df1, 'gpt-4', 'hpo_concepts', 'd', 10)
avg_sd(df1, 'gpt-4', 'hpo_concepts', 'd', 50)
avg_sd(df1, 'gpt-4', 'free_text', 'a', 10)
avg_sd(df1, 'gpt-4', 'free_text', 'a', 50)
avg_sd(df1, 'gpt-4', 'free_text', 'b', 10)
avg_sd(df1, 'gpt-4', 'free_text', 'b', 50)
avg_sd(df1, 'gpt-4', 'free_text', 'c', 10)
avg_sd(df1, 'gpt-4', 'free_text', 'c', 50)
avg_sd(df1, 'gpt-4', 'free_text', 'd', 10)
avg_sd(df1, 'gpt-4', 'free_text', 'd', 50)
avg_sd(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'a', 10)
avg_sd(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'a', 50)
avg_sd(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'b', 10)
avg_sd(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'b', 50)
avg_sd(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'c', 10)
avg_sd(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'c', 50)
avg_sd(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'd', 10)
avg_sd(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'd', 50)
avg_sd(df1, 'gpt-3.5-turbo', 'free_text', 'a', 10)
avg_sd(df1, 'gpt-3.5-turbo', 'free_text', 'a', 50)
avg_sd(df1, 'gpt-3.5-turbo', 'free_text', 'b', 10)
avg_sd(df1, 'gpt-3.5-turbo', 'free_text', 'b', 50)
avg_sd(df1, 'gpt-3.5-turbo', 'free_text', 'c', 10)
avg_sd(df1, 'gpt-3.5-turbo', 'free_text', 'c', 50)
avg_sd(df1, 'gpt-3.5-turbo', 'free_text', 'd', 10)
avg_sd(df1, 'gpt-3.5-turbo', 'free_text', 'd', 50)
avg_sd_acc(df1, 'gpt-4', 'hpo_concepts', 'a', 10)
avg_sd_acc(df1, 'gpt-4', 'hpo_concepts', 'a', 50)
avg_sd_acc(df1, 'gpt-4', 'hpo_concepts', 'b', 10)
avg_sd_acc(df1, 'gpt-4', 'hpo_concepts', 'b', 50)
avg_sd_acc(df1, 'gpt-4', 'hpo_concepts', 'c', 10)
avg_sd_acc(df1, 'gpt-4', 'hpo_concepts', 'c', 50)
avg_sd_acc(df1, 'gpt-4', 'hpo_concepts', 'd', 10)
avg_sd_acc(df1, 'gpt-4', 'hpo_concepts', 'd', 50)
avg_sd_acc(df1, 'gpt-4', 'free_text', 'a', 10)
avg_sd_acc(df1, 'gpt-4', 'free_text', 'a', 50)
avg_sd_acc(df1, 'gpt-4', 'free_text', 'b', 10)
avg_sd_acc(df1, 'gpt-4', 'free_text', 'b', 50)
avg_sd_acc(df1, 'gpt-4', 'free_text', 'c', 10)
avg_sd_acc(df1, 'gpt-4', 'free_text', 'c', 50)
avg_sd_acc(df1, 'gpt-4', 'free_text', 'd', 10)
avg_sd_acc(df1, 'gpt-4', 'free_text', 'd', 50)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'a', 10)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'a', 50)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'b', 10)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'b', 50)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'c', 10)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'c', 50)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'd', 10)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'hpo_concepts', 'd', 50)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'free_text', 'a', 10)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'free_text', 'a', 50)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'free_text', 'b', 10)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'free_text', 'b', 50)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'free_text', 'c', 10)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'free_text', 'c', 50)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'free_text', 'd', 10)
avg_sd_acc(df1, 'gpt-3.5-turbo', 'free_text', 'd', 50)
avg_sd_acc(df2, 'llama-2-7b-chat', 'hpo_concepts', 'd', 10)
avg_sd_acc(df2, 'llama-2-7b-chat', 'hpo_concepts', 'd', 50)
avg_sd_acc(df2, 'llama-2-7b-chat', 'free_text', 'd', 10)
avg_sd_acc(df2, 'llama-2-7b-chat', 'free_text', 'd', 50)
avg_sd_acc(df2, 'llama-2-13b-chat', 'hpo_concepts', 'd', 10)
avg_sd_acc(df2, 'llama-2-13b-chat', 'hpo_concepts', 'd', 50)
avg_sd_acc(df2, 'llama-2-13b-chat', 'free_text', 'd', 10)
avg_sd_acc(df2, 'llama-2-13b-chat', 'free_text', 'd', 50)
avg_sd_acc(df2, 'llama-2-70b-chat', 'hpo_concepts', 'd', 10)
avg_sd_acc(df2, 'llama-2-70b-chat', 'hpo_concepts', 'd', 50)
avg_sd_acc(df2, 'llama-2-70b-chat', 'free_text', 'd', 10)
avg_sd_acc(df2, 'llama-2-70b-chat', 'free_text', 'd', 50)
avg_sd(df2, 'llama-2-7b-chat', 'hpo_concepts', 'd', 10)
avg_sd(df2, 'llama-2-7b-chat', 'hpo_concepts', 'd', 50)
avg_sd(df2, 'llama-2-7b-chat', 'free_text', 'd', 10)
avg_sd(df2, 'llama-2-7b-chat', 'free_text', 'd', 50)
avg_sd(df2, 'llama-2-13b-chat', 'hpo_concepts', 'd', 10)
avg_sd(df2, 'llama-2-13b-chat', 'hpo_concepts', 'd', 50)
avg_sd(df2, 'llama-2-13b-chat', 'free_text', 'd', 10)
avg_sd(df2, 'llama-2-13b-chat', 'free_text', 'd', 50)
avg_sd(df2, 'llama-2-70b-chat', 'hpo_concepts', 'd', 10)
avg_sd(df2, 'llama-2-70b-chat', 'hpo_concepts', 'd', 50)
avg_sd(df2, 'llama-2-70b-chat', 'free_text', 'd', 10)
avg_sd(df2, 'llama-2-70b-chat', 'free_text', 'd', 50)
```
